### ISSUE TITLE
The same code in deleteDomain() and modifyDomain()

### ISSUE THREAD

**Issue by ihorbyra** [PowerPanel/Plugin-Examples#1]
Both of methods [**deleteDomain()** and **modifyDomain()**] have the same code.
For example:
`$result = array(
    'msg' => 'Domain has been successfully deleted',
    'status' => 'quarantine'
);`

`$this->setResult( $result );`

`return true;`

**Comment by PeterNotenboom** [comment]
Thanks for your issue!
Fixed it right away.
